import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const root = new URL('../', import.meta.url)
const source = (relativePath) => fs.readFileSync(new URL(relativePath, root), 'utf8')

test('persists one-time first-open onboarding state with user settings', () => {
  const preferences = source('lib/user-preferences.ts')
  assert.match(preferences, /onboardingComplete: boolean/)
  assert.match(preferences, /onboardingVersion: number/)
  assert.match(preferences, /onboardingComplete: false/)
  assert.match(preferences, /onboardingVersion: 2/)
})

test('renders a logo-first onboarding sequence that saves profile and language choices', () => {
  const onboarding = source('components/first-open-onboarding.tsx')
  assert.match(onboarding, /src="\/uncgpt\.png"/)
  assert.match(onboarding, /UncGPT/)
  assert.match(onboarding, /ONBOARDING_VERSION = 2/)
  assert.match(onboarding, /Get started/)
  assert.match(onboarding, /Create account/)
  assert.match(onboarding, /Enter your email/)
  assert.match(onboarding, /What&apos;s your name\?/)
  assert.match(onboarding, /Choose a username/)
  assert.match(onboarding, /Choose your language/)
  assert.match(onboarding, /\/api\/profile\/username/)
  assert.match(onboarding, /localStorage\.setItem\('uncgpt-language'/)
  assert.match(onboarding, /onboardingComplete: true/)
  assert.match(onboarding, /onboardingVersion: ONBOARDING_VERSION/)
  assert.match(onboarding, /LANGUAGE_OPTIONS/)
  assert.match(onboarding, /Globe2/)
  assert.match(onboarding, /SelectTrigger/)
  assert.match(onboarding, /SelectContent/)
  assert.match(onboarding, /Automatic \(device language\)/)
  assert.match(onboarding, /max-h-\[min\(52dvh,420px\)\]/)
  assert.match(onboarding, /language === 'auto'/)
  assert.doesNotMatch(onboarding, /role="radiogroup"/)
  assert.match(onboarding, /languageTransition/)
  assert.match(onboarding, /scale: \[1, 3\.4\]/)
  assert.match(onboarding, /scale: \[1, 5\.4\]/)
  assert.doesNotMatch(onboarding, /rounded-\[28px\].*bg-card/)
  assert.doesNotMatch(onboarding, /Get started' : `Setup/)
  assert.doesNotMatch(onboarding, /Sparkles/)
})

test('mounts onboarding only after account preferences hydrate and hides it after completion', () => {
  const workspace = source('app/chat-workspace.tsx')
  assert.match(workspace, /await useChatStore\.persist\.rehydrate\(\)/)
  assert.match(workspace, /shouldShowFirstOpenOnboarding\(\)/)
  assert.match(workspace, /onboardingReady && onboardingOpen/)
  assert.match(workspace, /<FirstOpenOnboarding/)
  assert.match(workspace, /setOnboardingOpen\(false\)/)
  assert.match(workspace, /settingsOpen && !onboardingOpen/)
})
