import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'

const root = new URL('../', import.meta.url)
const source = (relativePath) => fs.readFileSync(new URL(relativePath, root), 'utf8')

test('renders the dark Lunar welcome screen with first-party provider choices', () => {
  const authPanel = source('components/auth-panel.tsx')

  assert.match(authPanel, /useUiText/)
  assert.match(authPanel, /Welcome to Lunar/)
  assert.match(authPanel, /primaryProvider\.id/)
  assert.match(authPanel, /provider\.id === "discord"/)
  assert.match(authPanel, /"continueGithub"/)
  assert.match(authPanel, /t\("lastUsed"\)/)
  assert.match(authPanel, /t\("emailAddress"\)/)
  assert.match(authPanel, /t\("dontHaveAccount"\)/)
  assert.match(authPanel, /bg-\[#080909\]/)
  assert.match(authPanel, /font-serif/)
  assert.match(authPanel, /Continue with Email/)
  assert.match(authPanel, /\/api\/auth\/\$\{provider\}\/start/)
  assert.doesNotMatch(authPanel, /@clerk\/nextjs|useSignIn|useSignUp|signIn\.sso|Secured by Clerk|Development mode/)
  assert.doesNotMatch(authPanel, /type="password"|\.password\(/)
})

test('opens social sign-in in a new Safari context from an installed Home Screen app', () => {
  const authPanel = source('components/auth-panel.tsx')
  const manifest = source('app/manifest.ts')

  assert.match(authPanel, /display-mode: standalone/)
  assert.match(authPanel, /navigator as Navigator & \{ standalone\?: boolean \}/)
  assert.match(authPanel, /pendingProvider/)
  assert.match(authPanel, /providerDomains/)
  assert.match(authPanel, /“Lunar” Wants to Use/)
  assert.match(authPanel, /window\.open\(authUrl, "_blank"/)
  assert.match(authPanel, /setPendingProvider\(selectedProvider\)/)
  assert.match(manifest, /display: "standalone"/)
  assert.match(manifest, /start_url: "\/"/)
})

test('uses Lunar-owned server OAuth routes and never sends OAuth secrets to browser code', () => {
  const start = source('app/api/auth/[provider]/start/route.ts')
  const callback = source('app/api/auth/[provider]/callback/route.ts')

  assert.match(start, /accounts\.google\.com\/o\/oauth2\/v2\/auth/)
  assert.match(start, /discord\.com\/api\/oauth2\/authorize/)
  assert.match(start, /github\.com\/login\/oauth\/authorize/)
  assert.match(start, /beginLunarOAuth/)
  assert.match(callback, /validateLunarOAuthState/)
  assert.match(callback, /client_secret: config\.clientSecret/)
  assert.match(callback, /oauth2\.googleapis\.com\/token/)
  assert.match(callback, /discord\.com\/api\/oauth2\/token/)
  assert.match(callback, /github\.com\/login\/oauth\/access_token/)
  assert.match(callback, /email_verified !== true/)
  assert.match(callback, /profile\.verified !== true/)
  assert.match(callback, /lunarAuthSuccess/)
  assert.doesNotMatch(start, /NEXT_PUBLIC.*SECRET|client_secret/)
})

test('protects Lunar sessions and direct callbacks with signed cookies and CSRF state', () => {
  const auth = source('lib/lunar-auth.ts')
  const proxy = source('proxy.ts')
  const session = source('lib/auth.ts')
  const callback = source('app/api/auth/[provider]/callback/route.ts')

  assert.match(auth, /LUNAR_SESSION_COOKIE/)
  assert.match(auth, /new SignJWT/)
  assert.match(auth, /jwtVerify/)
  assert.match(auth, /httpOnly: true/)
  assert.match(auth, /sameSite: "lax"/)
  assert.match(auth, /validateLunarOAuthState/)
  assert.match(auth, /timingSafeEqual/)
  assert.match(auth, /LUNAR_AUTH_SECRET/)
  assert.match(proxy, /LUNAR_OAUTH_PATH/)
  assert.match(proxy, /getLunarSessionFromToken/)
  assert.match(proxy, /request\.cookies\.get\(LUNAR_SESSION_COOKIE\)/)
  assert.doesNotMatch(proxy, /getSession\(\)|clerkMiddleware|@clerk\/nextjs/)
  assert.match(session, /getLunarSession/)
  assert.match(auth, /code_challenge_method/)
  assert.match(auth, /codeVerifier/)
  assert.match(auth, /JSON\.stringify\(\{ state, codeVerifier \}/)
  assert.match(callback, /code_verifier/)
  assert.match(callback, /oauthFailure/)
  assert.match(callback, /clearLunarOAuthState\(response, provider\)/)
})

test('preserves existing user-owned data through a fail-closed legacy account bridge', () => {
  const session = source('lib/auth.ts')
  const bridge = source('lib/legacy-account-bridge.ts')
  const migration = source('SUPABASE_LUNAR_AUTH_IDENTITIES.sql')

  const callback = source('app/api/auth/[provider]/callback/route.ts')
  const lunarAuth = source('lib/lunar-auth.ts')
  assert.match(callback, /resolveLunarAccountScope/)
  assert.match(callback, /const accountScope = await resolveLunarAccountScope\(user\)/)
  assert.match(callback, /lunarAuthSuccess\(request, user, accountScope\)/)
  assert.match(session, /sub: session\.accountScope/)
  assert.match(lunarAuth, /account_scope: accountScope/)
  assert.match(lunarAuth, /isValidAccountScope\(payload\.account_scope, payload\.sub\)/)
  assert.match(bridge, /CLERK_SECRET_KEY/)
  assert.match(bridge, /provider_user_id/)
  assert.match(bridge, /email_address/)
  assert.match(bridge, /primary_email_address_id/)
  assert.match(bridge, /verification\?\.status === "verified"/)
  assert.match(bridge, /scopes\.length === 1/)
  assert.match(bridge, /ignoreDuplicates: true/)
  assert.match(bridge, /return user\.sub/)
  assert.doesNotMatch(bridge, /NEXT_PUBLIC.*CLERK_SECRET_KEY/)
  assert.match(migration, /create table if not exists public\.lunar_auth_identities/)
  assert.match(migration, /enable row level security/)
  assert.match(migration, /revoke all on table public\.lunar_auth_identities from anon, authenticated/)
  assert.match(migration, /lunar_auth_identities_no_client_access/)
})

test('removes Clerk from Lunar entry, callback, logout, and public consent pages', () => {
  const callback = source('app/sso-callback/page.tsx')
  const signup = source('app/signup/page.tsx')
  const login = source('app/login/page.tsx')
  const layout = source('app/layout.tsx')
  const logout = source('components/sign-out-button.tsx')
  const privacy = source('app/privacy/page.tsx')
  const terms = source('app/terms/page.tsx')

  assert.match(callback, /redirect\("\/login"\)/)
  assert.match(signup, /AuthPanel mode="sign-up"/)
  assert.match(login, /AuthPanel/)
  assert.doesNotMatch(layout, /ClerkProvider|@clerk\/nextjs/)
  assert.match(logout, /\/api\/auth\/logout/)
  assert.doesNotMatch(logout, /useClerk|@clerk\/nextjs/)
  assert.doesNotMatch(privacy, /Clerk/)
  assert.doesNotMatch(terms, /Clerk/)
  assert.equal(fs.existsSync(new URL('public/lunar-mark-transparent.png', root)), true)
})
