'use client'

import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'

const conversations = [{ username: 'uncgpt', text: 'Welcome to uncgpt. You can message people from their profiles.', time: 'now' }]

export function MessagesPage() {
  return <main className="min-h-screen bg-[#050505] px-5 py-8 text-white sm:px-10"><div className="mx-auto max-w-2xl"><div className="mb-8 flex items-center gap-4"><Link href="/" aria-label="Back to workspace" className="rounded-full p-2 text-white/55 transition hover:bg-white/10 hover:text-white"><ArrowLeft className="h-5 w-5" /></Link><div><p className="text-xs uppercase tracking-[0.22em] text-white/35">uncgpt</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Messages</h1></div></div><div className="mb-5 flex gap-2"><Link href="/notifications" className="rounded-full px-4 py-2 text-sm text-white/50 transition hover:bg-white/10 hover:text-white">Notifications</Link><Link href="/messages" className="rounded-full bg-white/12 px-4 py-2 text-sm text-white">Messages</Link></div><section className="overflow-hidden rounded-[26px] border border-white/10 bg-white/[0.035] shadow-2xl shadow-black/30">{conversations.map((conversation) => { const content = <><div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-full bg-indigo-500/20 text-indigo-200"><img src={`/api/profile/avatar?username=${encodeURIComponent(conversation.username)}`} alt={`@${conversation.username}`} className="h-full w-full object-cover" onError={(event) => { event.currentTarget.src = '/uncgpt.png' }} /></div><div className="min-w-0 flex-1"><p className="font-semibold">{conversation.username}</p><p className="mt-1 truncate text-sm text-white/55">{conversation.text}</p></div><span className="text-xs text-white/35">{conversation.time}</span>{conversation.username.toLowerCase() === 'uncgpt' && <span className="text-xs text-white/45">Messaging unavailable</span>}</>; return conversation.username.toLowerCase() === 'uncgpt' ? <div key={conversation.username} className="flex items-center gap-4 border-b border-white/[0.08] px-5 py-5 opacity-60 sm:px-7" aria-disabled="true">{content}</div> : <Link href={`/messages/${conversation.username}`} key={conversation.username} className="flex items-center gap-4 border-b border-white/[0.08] px-5 py-5 transition hover:bg-white/[0.06] sm:px-7">{content}</Link> })}</section></div></main>
}
