'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Bell, Check, MessageCircle, UserPlus } from 'lucide-react'

type Notification = { id: string; kind: 'follow' | 'message'; username: string; text: string; time: string; added?: boolean }

const seed: Notification[] = []

export function NotificationsPage() {
  const [items, setItems] = useState<Notification[]>(seed)
  useEffect(() => { try { const saved = localStorage.getItem('uncgpt-notifications'); if (saved) setItems(JSON.parse(saved).filter((item: Notification) => item?.username?.toLowerCase() !== 'uncgpt')) } catch {} }, [])
  const update = (next: Notification[]) => { setItems(next); try { localStorage.setItem('uncgpt-notifications', JSON.stringify(next)) } catch {} }
  return <main className="min-h-screen bg-[#050505] px-4 py-6 text-white sm:px-8 sm:py-10"><div className="mx-auto w-full max-w-3xl"><div className="mb-8 flex items-center gap-4"><Link href="/" aria-label="Back to workspace" className="rounded-full p-2 text-white/55 transition hover:bg-white/10 hover:text-white"><ArrowLeft className="h-5 w-5" /></Link><div><p className="text-xs uppercase tracking-[0.22em] text-white/35">uncgpt</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Notifications</h1></div></div><div className="mb-5 flex gap-2"><Link href="/notifications" className="rounded-full bg-white/12 px-4 py-2 text-sm text-white">Notifications</Link><Link href="/messages" className="rounded-full px-4 py-2 text-sm text-white/50 transition hover:bg-white/10 hover:text-white">Messages</Link></div><section className="overflow-hidden rounded-[22px] border border-white/10 bg-white/[0.035] shadow-2xl shadow-black/30">{items.map((item) => <article key={item.id} className="border-b border-white/[0.08] px-5 py-5 last:border-b-0 sm:px-7"><div className="flex gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center overflow-hidden rounded-full bg-white/[0.09] text-white/75"><img src={`/api/profile/avatar?username=${encodeURIComponent(item.username)}`} alt={`@${item.username}`} className="h-full w-full object-cover" onError={(event) => { event.currentTarget.src = '/uncgpt.png' }} /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="text-[16px] leading-6"><strong className="font-semibold">{item.username}</strong> <span className="text-white/55">{item.kind === 'follow' ? 'wants to follow you' : 'sent you a message'}</span></p><span className="shrink-0 text-xs text-white/35">{item.time}</span></div><p className="mt-1 text-sm leading-6 text-white/60">{item.text}</p>{item.kind === 'follow' ? <button onClick={() => update(items.map((entry) => entry.id === item.id ? { ...entry, added: !entry.added } : entry))} className="mt-4 inline-flex items-center gap-2 rounded-full bg-indigo-500 px-4 py-2 text-sm font-medium transition hover:bg-indigo-400">{item.added ? <Check className="h-4 w-4" /> : <UserPlus className="h-4 w-4" />}{item.added ? 'Added back' : 'Add back'}</button> : item.username.toLowerCase() === 'uncgpt' ? <span className="mt-4 inline-flex items-center gap-2 rounded-full border border-white/10 px-4 py-2 text-sm text-white/45">Official account cannot be messaged</span> : <Link href={`/messages/${encodeURIComponent(item.username)}`} className="mt-4 inline-flex items-center gap-2 rounded-full bg-indigo-500 px-4 py-2 text-sm font-medium transition hover:bg-indigo-400"><MessageCircle className="h-4 w-4" />Open message</Link>}</div></div></article>)}{items.length === 0 && <div className="px-6 py-16 text-center text-sm text-white/45">You’re all caught up.</div>}</section></div></main>
}
